### ISSUE TITLE
Adding apps is sporadic

### ISSUE THREAD

**Issue by scottw12** [vanjarosoftware/Vanjaro.Platform#1942]
**Product & Version**
Vanjaro 1.2.0
**Describe the bug**
After upgrading to 1.2.0  We are having problems with most applications. About 70% of the time when you drag an application block it ends up rendering as an image block.

**Screenshots**
http://somup.com/crlVcM0u8p

**Additional context**
Browser debug tools error log:
uxmanager.min.js?cdv=109:20 
        
       Uncaught TypeError: e.getEl is not a function
    at r.<anonymous> (uxmanager.min.js?cdv=109:20)
    at v (uxmanager.min.js?cdv=109:3)
    at m (uxmanager.min.js?cdv=109:3)
    at d (uxmanager.min.js?cdv=109:3)
    at r.c.trigger (uxmanager.min.js?cdv=109:3)
    at r.handleDragEnd (uxmanager.min.js?cdv=109:3)
    at Ke (uxmanager.min.js?cdv=109:3)
    at HTMLDivElement.<anonymous> (uxmanager.min.js?cdv=109:3)
    at HTMLDivElement.<anonymous> (uxmanager.min.js?cdv=109:3)
    at HTMLDivElement.e (uxmanager.min.js?cdv=109:3)
(anonymous) @ uxmanager.min.js?cdv=109:20
v @ uxmanager.min.js?cdv=109:3
m @ uxmanager.min.js?cdv=109:3
d @ uxmanager.min.js?cdv=109:3
c.trigger @ uxmanager.min.js?cdv=109:3
handleDragEnd @ uxmanager.min.js?cdv=109:3
Ke @ uxmanager.min.js?cdv=109:3
(anonymous) @ uxmanager.min.js?cdv=109:3
(anonymous) @ uxmanager.min.js?cdv=109:3
e @ uxmanager.min.js?cdv=109:3

**Comment by Gaganbird** [comment]
It has been fixed in https://github.com/vanjarosoftware/Vanjaro.Platform/pull/1940 

In the meantime please drag app from its text not image. See https://watch.screencastify.com/v/8PpuRiwgJbEXq6vEZ9q4
